name: 'Webhook'
author: Josa Gesell <josa@gesell.me>
description: |
  Trigger Webkhooks
inputs:
  url:
    required: true
  method:
    default: 'POST'
runs:
  using: 'docker'
  image: 'docker://josa/gh-action-webhook:0.1.0'
branding:
  icon: 'refresh-ccw'
  color: 'blue'
