name: 'Webhook'
author: Josa Gesell <josa@gesell.me>
description: |
  Trigger Webkhooks
inputs:
  url:
    description: 'Request URL.'
    required: true
  method:
    description: 'GET, POST, PUT or DELETE'
    required: false
    default: 'POST'
  data:
    description: 'Request Body.'
    required: false
  authorization:
    description: 'Set `Authorization` header.'
    required: false
  accept:
    description: 'Set `Accept` header.'
    required: false
  content_type:
    description: 'Set `Content-Type` header.'
    required: false
runs:
  using: 'docker'
  image: 'docker://josa/gh-action-webhook:0.1.0'
branding:
  icon: 'refresh-ccw'
  color: 'blue'
