name: Example
on:
  push:
    branches: [ master ]
jobs:
  test:
    name: Run Webhooks
    runs-on: ubuntu-latest
    steps:
      - uses: josa42/gh-action-webhook/build@master
        with:
          url: http://httpbin.org/post
      - uses: josa42/gh-action-webhook/release@master
        with:
          url: http://httpbin.org/post
      - uses: josa42/gh-action-webhook/latest@master
        with:
          url: http://httpbin.org/post
      - uses: josa42/gh-action-webhook/latest@master
        with:
          url: http://httpbin.org/post
          data: '{ "data": "Hallo Welt" }'
      - uses: josa42/gh-action-webhook@master
        with:
          url: http://httpbin.org/post
          data: '{ "data": "TEST" }'
          authorization: 'Bearer ${{ secrets.TOKEN }}'


