name: Example
on:
  push:
    branches: [ master ]
jobs:
  test:
    name: Run Webhooks
    runs-on: ubuntu-latest
    steps:
      - uses: 'josa42/gh-action-webhook/release@0.1.0'
        with: { url: 'https://httpbin.org/post' }
      - uses: 'josa42/gh-action-webhook/latest@master'
        with: { url: 'https://httpbin.org/post' }
      - uses: 'josa42/gh-action-webhook/latest@master'
        with:
          url:  'https://hooks.slack.com/services/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'
          data: '{ "text": "Hello World! (from: ${{github.repository}} / ${{github.ref}})" }'


