name: Tag
on:
  push:
    tags: [ '*' ]
jobs:
  test:
    name: Test and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Test: POST (ssl)'
        uses: ./build
        with: { url: 'https://httpbin.org/post' }
      - uses: 'josa42/gh-action-docker/latest@master'
        with:
          image: 'josa/gh-action-webhook'
          docker_username: '${{ secrets.DOCKER_USERNAME }}'
          docker_password: '${{ secrets.DOCKER_PASSWORD }}'

